### ISSUE TITLE
Maybe use concept list from Concepticon after all?

### ISSUE THREAD

**Issue by xrotwang** [lexibank/zgraggenmadang#2]
I just checked, and the mapping in `etc/concepts` seem to be exactly the same as in https://github.com/clld/concepticon-data/blob/master/concepticondata/conceptlists/Zgraggen-1980-380.tsv - except for cases where the concepticon list has received new mappings of so far unmapped concepts.

**Comment by LinguList** [comment]
yes, I agree, @tresoldi can also look into this, as he added the data by then.

**Comment by SimonGreenhill** [comment]
Yes -- the concepticon mapping is more likely to be updated and stay up to date, so I think we should prefer those instead of local ones in etc/

**Comment by SimonGreenhill** [comment]
removed in https://github.com/lexibank/zgraggenmadang/commit/81d899363efecb57a5e0990f4c9987bcd8bde81e

**Comment by LinguList** [comment]
careful. The curent solution still uses concepts.csv! The rpoblem is that the matches aren't exact, so I had to map both the concepts in concepticon and the ones not there as fallback. So this will destroy the current setting.

**Comment by tresoldi** [comment]
I could take of it tomorrow, when I update the code for using the concept lists in nagano and yang. If so, just reopen the issue and assign it to me.

**Comment by LinguList** [comment]
this works in my opinion, but we just need to re-add the conceptlist, if you check my code, that also uses the orthography profile (with zero errors this time).

**Comment by SimonGreenhill** [comment]
yes, I just realised that, sorry.

**Comment by tresoldi** [comment]
I put back the concept list, but there is now some error in the code where the same form ("aN") is propagated to all entries, I will check right now.

**Comment by LinguList** [comment]
wait please, let me check that I have pushed everything, was perfectly working for me yesterday!

**Comment by tresoldi** [comment]
It was running, but you had already pushed with the repeated value: https://github.com/lexibank/zgraggenmadang/commit/2de70de674a3b13cd59b9c52f0903003d81d6cf4

Looking at code now, I am pretty sure it is because `add_lexemes` is getting `counterpart` as value, which was the previous code. But I'll wait.

**Comment by LinguList** [comment]
Allright, go ahead, the error was also in my version.

**Comment by LinguList** [comment]
Ah, and important: delete all statements that MAKE tokens manually, we don't need them with the orthography profile. And if the orthoprofile is checked now, make please also sure that 

* it runs perfectly, without errors, and
* no `_` is used, but `+` instead as a morpheme segmentation marker

**Comment by tresoldi** [comment]
I am sorry but I don't get what you mean my manual tokenization in my previous code. What I had was reading the COUNTERPART column from the raw data and using `self.tokenizer`. I suppose the lingpy wordlist would not be necessary if we don't want the automatic cognate judgement anymore, but the tokenization was already done using the profile.

If you refer to the parentheses removal with a regular expression, it is impossible to do so with an orthographic profile (unless, of course, we list all the cases for grammatical notes), because only (a) parentheses at the end of the string, (b) preceded by a space and (c) with a variable number of characters inside should be removed -- all other parentheses are phonological material. This was explained in the comment I had back then.

**Comment by tresoldi** [comment]
I've pushed my changes, please check and let me know.

**Comment by LinguList** [comment]
> I am sorry but I don't get what you mean my manual tokenization in my previous code. What I had was reading the COUNTERPART column from the raw data and using self.tokenizer. I suppose the lingpy wordlist would not be necessary if we don't want the automatic cognate judgement anymore, but the tokenization was already done using the profile.

This is done automatically, if you only add the counterpart, and you specify an orthography profile. So you do not need to create any tokens "manually", i.e., within your code!

**Comment by LinguList** [comment]
> If you refer to the parentheses removal with a regular expression, it is impossible to do so with an orthographic profile (unless, of course, we list all the cases for grammatical notes), because only (a) parentheses at the end of the string, (b) preceded by a space and (c) with a variable number of characters inside should be removed -- all other parentheses are phonological material. This was explained in the comment I had back then.

You know the basic drill of lexibank, right?

* value -> form , using functions clean_form and lingpy's clean_string, which also includes a splitting routine, and a stripping of brackets, so you need to override that function
* form -> tokens, using the orthography profile

so instead of fiddling in the code itself, you should overwrite the existing functions that turn a value into a form, and that turn a form into tokens.

**Comment by LinguList** [comment]
Had a look. The general problem is that the orthography profile is not used, and that you do not use the internal lexibank functions to clean the string, etc. Things we wanted to avoid. 

So the relevant functions to check here are: `Dataset.clean_form`, see allenbai, where I used that, and also clldutils.text, with `strip_brackets`, and `split_text` (or similar). Both offer a wealth of standardized possibilities to handle these cases more consistently. Segments should be procuded from the existing orthoprofile, not from using lingpy's tokenizer.

**Comment by tresoldi** [comment]
Ok, I see the point having `.add_lexeme()` automatically segmenting the values, but how is calling `Dataset.tokenizer()` a "manual segmentation using lingpy"? Redundant at this point, granted, but isn't it exactly what is called internally?

As for `clean_form()`, I could follow the standard now, it was not possible before because we needed the clean forms in advance in order to run the automatic cognate judgment analysis. Actually, is not even needed anymore.

Just pushed the new version, please check.

**Comment by LinguList** [comment]
Don't get mad about the use of words I have, please, but I thought it was clear, also if you check all the issues we had int eh past, with the bug-fix I added to modify clean_form, to not produce the form two times, etc., that we no longer clean in an unstandardized way, right? So we should use similar routines, and this is the goal for all lexibank datasets for the new version, specifically in those cases where segmentation is involved.

Exceptions are those datasets which are already segmented, such as cihui, and to some degree allenbai.

**Comment by tresoldi** [comment]
Not mad, don't worry, just really puzzled. :wink: 

Just please check if it is ok now, so we can close the issue.

**Comment by LinguList** [comment]
Nice, even without lingpy import. Thanks!

**Comment by SimonGreenhill** [comment]
Awesome, thanks for slogging through and sorting this out @tresoldi !
